os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
script:
- mvn install
before_install:
- openssl aes-256-cbc -K $encrypted_c40598b13556_key -iv $encrypted_c40598b13556_iv
  -in runtime/src/test/resources/test-variables.properties.enc -out runtime/src/test/resources/test-variables.properties
  -d
- bash .util/build_xatkit.sh
notifications:
  slack:
    secure: NfuaqlTPBTE1BlMXlkh9zDvToVXoZO6F4aty2zEKJyToRXrKnllAN5wRRLhp9GjBWO1NA6rGf2xfi8F4G4ZmMOMZauV8qarAswYYVlP2yq12zV/JdLooy/18DIGdHWlZ+31LQ6isJ3Gj4vITqClW/Zu2nbjNwYcZ2YJBgg/mQk9Xi4+JXu7wFV4eizgZxSffpr+Dzp7K6hqTWHjRcVMGbf3wLm99Q0HEFvszbYBYeA9CQBPS6WAp6wCbbqjMrGPWVLo7//Xbk+ugloBF7wdF+OYy+mrynzYsgtLh1LqCnL9KJKM6IBm4IzOrXImQ8XzQzlcS89keQbvf+Pq4lyYAYVmtVPeGJQPZ2S4xwOHmUNoZl7GYopgDywF7VAgMtGy9PA7aWS0WFndlXFF4PO5S3ztyy0E+H2kULGkBOVxoORWPUc2TegvGQolQX349fi1FZdWDTiRaaGGnEqHGHvfn6yVDI1w7+8LSui4kk5MTNHrt/9TLknpdH7Xu9o8ThKqYZZEkRg50oroutcPXe+KpGWKdXJ+bZ3EDA5onEE/0tXXeE5mEMLfm8hMPx3OBTr+AwgVcaCotordIjzZjaFj42Dv1VUKKEr1U9K3X29UkmMmm4gLScRmAF/WStaaipoPMiaDitDqYuLfabSi080aSexZzh/NY2QHkMnuEcmiqdfc=
