os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- openssl aes-256-cbc -K $encrypted_c40598b13556_key -iv $encrypted_c40598b13556_iv
  -in runtime/src/test/resources/test-variables.properties.enc -out runtime/src/test/resources/test-variables.properties
  -d
- bash .util/build_xatkit.sh
- bash .util/build_chat-platform.sh
script:
- mvn install
notifications:
  slack:
    secure: fxKAiJ4XPoOTMgv8Fvg6AmlTB61PbtR3RLk5xlhpwAjTLpsofAFiQqKAJk/2HaeC5B0CDpnNAV2t2Y5WbYcAsWGZkORWgA1HeRKP7A14znTqZXsFpzHp0SGhRvVhBm4dVNC2mL3D/RTDIEbZFWYjPeWZY9x8SK9gY/BLZ4Lzd1oQ2rV1EP+eAfpjMXtszWpMfhOTbhumV3f2hk+UNvj3u1s4CW5/adCzOLMZEIOQDiVpuPVx29BD5a+TqOa6DovZTdB+q7EWblzrhILMOnoPMt8eofi57hCWot1cmNwLhcaTDy0DLyoIblrNG3E31dlWvZayPv+P+nDQospBwLm17OMrYr+EDayJbKtwKw5a4PzbIGGjJgH1mzzmHSheCj3Tk3+s6JfyxbCT8HJZP6/rqWKnwQgh5OCvJacMueGPUNzICGY7YLUfSC6+du1+58lKZZX9zG1MUF+huS0QeNJEBWHIs7KyKj+Qk9d/Cxq/53otsBIgX/d6Qv7gTlhTLGhMFWQ6uJ7+J6bOLu2uasnIj2Yv+zX+wwNEiLBQHB658xh0jHmxsGmuRYra2xqIVgaEYgKJtvT09LiwzmxP9asy26A42zWRxUoH5TtbSIIjHwmdEE1s2cw6J4TAZ7CwA+f6Z6siqNEnicx66m9PvYc8BcOpDSbvJObyJCjpVbLW8pI=
